#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "Usage: `basename $0` <user-to-add> <DOMAIN> <initial-tmp-user-password> <user-password> <User First Name> <User Last Name> <
Admin Password> <group to add user one of: vpn|vpnsvc|vpnsvcadmin|vpnsvcqa|vpnsvcdevadmin"
  exit 0
fi

#create a user and add them to the right groups
echo $3 | ipa user-add $1 --first=$5 --last=$6 --homedir=/home/$1 --shell=/bin/bash --password
if [ "$8" == "vpn" ]; then
        ipa group-add-member vpn --users=$1
elif [ "$8" == "vpnsvc" ]; then
        ipa group-add-member vpn --users=$1
        ipa group-add-member svc_accounts --users=$1
elif [ "$8" == "vpnsvcdevqa" ]; then
        ipa group-add-member vpn --users=$1
        ipa group-add-member svc_accounts --users=$1
        ipa group-add-member devqa --users=$1
elif [ "$8" == "vpnsvcdevadmin" ]; then
        ipa group-add-member vpn --users=$1
        ipa group-add-member svc_accounts --users=$1
        ipa group-add-member devadmin --users=$1
elif [ "$8" == "vpnsvcadmin" ]; then
        ipa group-add-member vpn --users=$1
        ipa group-add-member svc_accounts --users=$1
        ipa group-add-member admins --users=$1
else
        echo "The account is not in the vpn, svc_accounts, or admins group"
fi

./mkuser $1 $2 $3 $4

# reset to admin user
echo $7 | kinit admin
